FROM owncloudci/nodejs:latest@sha256:fe0523d33406c57053721f1290396cbc5abe9aa063e63c88a523dc3a97dbf3c3

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Chromium"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/chromium"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/chromium"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/chromium"

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y chromium-browser && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
