FROM owncloudci/nodejs:latest@sha256:d040d2b1256c32e2e699ca2760851260ca400a1d30329c6105f76f43bb8c0db6

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI Chromium"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/chromium"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/chromium"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/chromium"

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y chromium-browser && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
